"""agrego plazo subasta

Revision ID: 7db29d6575af
Revises: 6462956d7fe7
Create Date: 2024-09-18 23:15:09.087823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db29d6575af'
down_revision = '6462956d7fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=False, server_default=sa.text("(now() + interval '7 day')")))
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('end_time', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###
